parameters:
  name: ""
  variablesFile: ""
  environmentName: ""
  azureSubscription: ""
  artifactDropName: drop
  aadVariableGroupName: ""
  

jobs:
  - deployment: Deploy
    displayName: ${{ parameters.name }}
    variables:
      - group: ${{ parameters.aadVariableGroupName }}
      - template: ${{ parameters.variablesFile }}
    pool:
      vmImage: ${{ variables.vmImage }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                action: "Create Or Update Resource Group"
                resourceGroupName: ${{ variables.resourceGroupName }}
                location: ${{ variables.location }}
                templateLocation: "Linked artifact"
                csmFile: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/scm-resources-api-dotnetcore.json
                overrideParameters: > 
                  -sku ${{ variables.appServicePlanSKU }} -webAppName ${{ variables.apiAppName }} -use32bitworker ${{ variables.use32bitworker }} 
                  -alwaysOn ${{ variables.alwaysOn }} -storageAccountName ${{ variables.storageAccountName }} -functionAppName ${{ variables.resizerFunctionName }} 
                  -applicationInsightsName ${{ variables.applicationInsightsName }} -serviceBusNamespaceName ${{ variables.serviceBusNamespaceName }}
                  -aadInstance ${{ variables.aadInstance }} -aadClientId $(aadApiClientId) -aadTenantId $(aadTenantId) -aadDomain $(aadDomain) -aadClientIdUri $(aadApiClientIdUri)
            - task: AzureRmWebAppDeployment@4
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: apiApp
                webAppName: ${{ variables.apiAppName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/Adc.Scm.Resources.Api.zip
            - task: AzureRmWebAppDeployment@4
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: apiApp
                webAppName: ${{ variables.resizerFunctionName }}
                package: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/Adc.Scm.Resources.ImageResizer.zip
