parameters:
  name: ""
  variablesFile: ""
  environmentName: ""
  azureSubscription: ""
  artifactDropName: drop

jobs:
  - deployment: Deploy
    displayName: ${{ parameters.name }}
    variables:
      - template: ${{ parameters.variablesFile }}
    pool:
      vmImage: ${{ variables.vmImage }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureResourceGroupDeployment@2
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                action: "Create Or Update Resource Group"
                resourceGroupName: ${{ variables.resourceGroupName }}
                location: ${{ variables.location }}
                templateLocation: "Linked artifact"
                csmFile: $(Pipeline.Workspace)/${{ parameters.artifactDropName }}/scm-common.json
                overrideParameters: -applicationInsightsName ${{ variables.applicationInsightsName }}
