parameters:
  artifactDropName: drop
  environmentServiceNameAzureRM: ""
  variableGroupName: ""
  environmentName: ADC-DAY8-SCM-DEV

jobs:
  - job: Build
    displayName: TearDown(!) Scm Common / Infrstructure
    variables:
      - group: ${{ parameters.variableGroupName }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: "0.12.24"
      - task: TerraformTaskV1@0
        displayName: Terraform Init
        inputs:
          provider: "azurerm"
          command: "init"
          workingDirectory: "$(System.DefaultWorkingDirectory)/day8/terraform"
          backendServiceArm: ${{ parameters.environmentServiceNameAzureRM }}
          backendAzureRmResourceGroupName: $(TFRESOURCEGROUPNAME)
          backendAzureRmStorageAccountName: $(TFSTORAGEACCOUNT)
          backendAzureRmContainerName: $(TFCONTAINERNAME)
          backendAzureRmKey: $(TFSTORAGEKEY)
      - task: TerraformTaskV1@0
        displayName: Terraform Destroy
        inputs:
          provider: "azurerm"
          command: "destroy"
          workingDirectory: "$(System.DefaultWorkingDirectory)/day8/terraform"
          commandOptions: '-var="location=$(LOCATION)" -var="prefix=$(PREFIX)" -var="env=$(ENV)" -var="app_insights_name=$(APPINSIGHTSNAME)" -var="keyvault_name=$(KEYVAULTNAME)" -var="keyvault_identity_name=$(KEYVAULTIDENTITYNAME)" -var="aks_cluster_name=$(AKSCLUSTERNAME)" -var="sqldbusername=$(SQLDBUSERNAME)" -var="sqldbpassword=$(SQLDBPASSWORD)" -var="sqlservername=$(SQLSERVERNAME)" -var="sqldbname=$(SQLDBNAME)" -var="servicebus_namespace_name=$(SERVICEBUSNAMESPACENAME)" -var="aadclientid=$(AADCLIENTID)" -var="aadclientiduri=$(AADCLIENTIDURI)" -var="devops_serviceconnectionid=$(DEVOPSSERVICECONNECTIONID)" -var="devops_projectid=$(DEVOPSPROJECTID)" -var="devops_pat=$(DEVOPSPAT)" -var="devops_orgurl=$(DEVOPSORGURL)" -var="devops_keyvaultgroupname=$(DEVOPSKEYVAULTGROUP)" -auto-approve'
          environmentServiceNameAzureRM: ${{ parameters.environmentServiceNameAzureRM }}

