apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-resources
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-headers: 'Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Accept-Language'
    nginx.ingress.kubernetes.io/cors-max-age: '600'
    nginx.ingress.kubernetes.io/proxy-body-size: '12m'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
    - host: #{YOUR_HOST_NAME}#
      http:
        paths:
          - path: /api/resources(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: resourcesapi
                port:
                  number: 8080
